language: r
cache: packages

r:
  - release
  - devel

sudo: false

addons:
  apt:
    packages:
      - qpdf

r_build_args: " --compact-vignettes=gs+qpdf"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

notifications:
  email:
    on_success: change
    on_failure: always
